name: Push Variables to Aruba Central

on:
  push:
    branches: [ main ]
    paths:
      - 'vars.json'
  workflow_dispatch:

jobs:
  deploy-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Variable Upload Script
        env:
          CENTRAL_ACCESS_TOKEN: ${{ secrets.CENTRAL_ACCESS_TOKEN }}
          ARUBA_GROUP_NAME: "Test-new"
        run: python upload_vars.py
